CREATE DATABASE BATON_main_database;
CREATE USER IF NOT EXISTS BATON_user IDENTIFIED BY '123BGhj23jkL0';

CREATE TABLE IF NOT EXISTS user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(10) NOT NULL ,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

GRANT ALL ON BATON_main_database.* TO BATON_user;